# Generated by Django 2.2.6 on 2019-12-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownrecipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
