# Generated by Django 2.2.6 on 2019-12-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownrecipe', '0002_auto_20191206_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('fk_login', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ownrecipe.Login')),
            ],
        ),
    ]
